### ISSUE TITLE
Want to test safety against hardware injections

### ISSUE THREAD

**Issue by duncanmmacleod** [gwdetchar/hveto#10]
`hveto` should provide built-in functionality to test safety against hardware injections.

The best option for this is probably to specify a hardware injections flag in the config file,

``` ini
[safety]
hardware-injections-flag = %(IFO)s:ODC-INJECTION_TRANSIENT:1
safety-threshold = ...
```

then use the segments from DQSegDB to test safety.

@areeda, @jrsmith02, how is this done in the matlab implementation?

**Comment by jrsmith02** [comment]
Safety studies are accomplished in hveto in a somewhat hacky way for O1. 1) someone makes injections and records the times, frequencies, and SNRs. 2) we look at the STRAIN Omicron triggers and identify the times, frequencies, and SNRs that correspond to those injections, as a precise record of the injected triggers. 3) we run regular hveto on a period of time containing those injections and consider the Omicron triggers corresponding to the injections as the primary channel (this is done mainly to make nice plots). 4) we run hveto_safety.m on those injections and this identifies channels that should be considered unsafe.

More details can be found here: https://wiki.ligo.org/DetChar/SafetyStudiesER8 and I'm happy to answer any questions.

**Comment by duncanmmacleod** [comment]
@jrsmith02, for this feature I was mainly thinking about including safety as a standard part of the hveto analysis, meaning we have to include injection times in the main flow somehow.

It sounds like from your post that injections are recorded using the loudest nearby trigger, so that an aux channel matches an injection if it has a trigger in a given window around the injection GPS (i.e. not using a GPS window for the injection, rather a single time).

This could all be done in the main flow by reading in injection segments (or accessing from the database, using the primary to identify the loudest nearby trigger), then comparing aux to those times.

**Comment by jrsmith02** [comment]
That is true and would work well if very loud detchar injections were done sporadically throughout the run. In ER8 and prior to O1 they were done in one big bunch over some tens of minutes, so we did stand alone safety studies on those times.

**Comment by duncanmmacleod** [comment]
@jrsmith02, are you suggesting my plan won't work when they are done in a big bunch, as done in ER8/O1? If so, why is that?

**Comment by jrsmith02** [comment]
I'm saying that if they are done in bunches before and after the run, two offline runs will do the job, and the continuous checking of safety wouldn't have any or enough injections to make decent statistics.

**Comment by duncanmmacleod** [comment]
ah ok, so you're saying that including it in the regular analysis is not likely to be useful. But, you're not saying that it would incorrect, right?

**Comment by jrsmith02** [comment]
That is right. It might be useful, but it would take coordination with the hardware injection team to make it so.

**Comment by areeda** [comment]
Done in separate repo dependent on this one
