### ISSUE TITLE
Errors on reading cache files

### ISSUE THREAD

**Issue by young-min** [gwdetchar/hveto#119]
When using --primary-cache and --auxiliary-cache option, 
"read_cache" is not working and the following error messages are shown,

Traceback (most recent call last):
  File "/data/kagra/home/kagradet/.local/bin/hveto", line 242, in <module>
    acache = read_cache(args.auxiliary_cache)
  File "/data/kagra/home/kagradet/.local/lib/python2.7/site-packages/gwpy/io/cache.py", line 151, in read_cache
    with open(file_path(cachefile), 'r') as fobj:
  File "/data/kagra/home/kagradet/.local/lib/python2.7/site-packages/gwpy/io/utils.py", line 201, in file_path
    raise ValueError("Cannot parse file name for {!r}".format(fobj))
ValueError: Cannot parse file name for ['/data/kagra/home/kagradet/hveto/test/testrun00/K1-aux-Cache-12358.lcf']

The problem is that args.auxiliary_cache and args.primary_cache are given by the arguments --primary-cache, --auxiliary-cache as a list of files.
'read_cache' must have a cache file, not the list of the files.

In addition, when read_cache(cachefile) runs, it works as expected but the following error messages are shown.
XLAL Error - new_tagLIGOTimeGPS__SWIG_3 (swiglal_python.c:10946): 'IMC_CAV_ERR_OUT_DQ_OMICRON' is not a valid LIGOTimeGPS
It looks unexpected warning messages.

And the last error is a tiny typo as follows,

in bin/hveto
line 362:        auxcache = [e for e in cache if Path(e).name.startswith(match)]
must be -->
line 362:        auxcache = [e for e in acache if Path(e).name.startswith(match)]

cache is not defined, and 'cache' must be 'acache'.

**Comment by young-min** [comment]
This error is not issued when using automatically generated caches except using --primary-cache and --auxiliary-cache.

**Comment by alurban** [comment]
@young-min, thank you for reporting this, I've opened #120 to resolve this issue.
