### ISSUE TITLE
Unsafe channel not being taken out

### ISSUE THREAD

**Issue by jrsmith02** [gwdetchar/hveto#91]
The channel H1:SUS-ETMY_L1_NOISEMON_LL_OUT_DQ wins round 1 and other rounds but is in the config file when I click on how was this page generated.

The page: https://ldas-jobs.ligo-wa.caltech.edu/~detchar/summary/day/20181104/detchar/hveto/

The config: config: https://ldas-jobs.ligo-wa.caltech.edu/~detchar/hveto/day/20181104/latest/about/

So the channel is clearly in the unsafe list, but does not get taken out of hveto.

**Comment by alurban** [comment]
@jrsmith02, as we discussed on Slack, this issue was due to `NOISEMON` channels being left out of the unsafe channel list under the production hveto runs, see the [`ligo-monitors`](https://git.ligo.org/detchar/ligo-monitors/merge_requests/12) repo for more information.
